var webpack = require('webpack'); 

module.exports = {
context: __dirname + '/app', //our applications source files   'SOURCES''
entry: {
    app: './app.js', //the main file that bootstraps our angular application 
    vendor: ['angular']
},
output: {
    path: __dirname + '/public/js', //where our bundle files are saved after they are generated by Webpack 'SINKS''
    filename: 'app.bundle.js'
},
plugins: [
    new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"vendor",/* filename= */"vendor.bundle.js") //splits application code and third party code into separate files. 'FILTERS'
]
};